create table topic (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  normalized_name varchar(255) not null,
  created_at timestamp with time zone not null,
  constraint uk_topic_name unique (name),
  constraint uk_topic_normalized_name unique (normalized_name)
);
create table question (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references topic(id),
  statement text not null,
  correct_index integer not null check (correct_index between 0 and 4),
  explanation text not null,
  created_at timestamp with time zone not null
);
create table question_option (
  question_id bigint not null references question(id) on delete cascade,
  option_order integer not null,
  option_text text not null,
  primary key (question_id, option_order)
);
create table study_material (
  id bigint generated by default as identity primary key,
  title varchar(500) not null,
  description text,
  type varchar(30) not null,
  file_name varchar(500),
  stored_path varchar(1000),
  original_url varchar(2048),
  size_bytes bigint not null,
  status varchar(30) not null,
  failure_reason varchar(1000),
  uploaded_at timestamp with time zone not null,
  processed_at timestamp with time zone
);
create table study_chunk (
  id bigint generated by default as identity primary key,
  material_id bigint not null references study_material(id) on delete cascade,
  chunk_index integer not null,
  chapter varchar(500),
  content text not null,
  token_count integer not null,
  embedding_json text not null,
  created_at timestamp with time zone not null,
  constraint uk_material_chunk unique(material_id, chunk_index)
);
create index idx_question_topic on question(topic_id);
create index idx_chunk_material on study_chunk(material_id);
create index idx_material_status on study_material(status);
