create table answer_history (
  id bigint generated by default as identity primary key,
  question_id bigint not null references question(id) on delete cascade,
  selected_answer integer not null check (selected_answer between 0 and 4),
  correct boolean not null,
  answered_at timestamp with time zone not null
);

create index idx_answer_history_question on answer_history(question_id);
create index idx_answer_history_answered_at on answer_history(answered_at desc);
