create table exam_notice (
  id bigint generated by default as identity primary key,
  material_id bigint not null unique references study_material(id) on delete cascade,
  status varchar(30) not null,
  processed_batches integer not null default 0,
  total_batches integer not null default 0,
  analysis_json text,
  failure_reason varchar(1000),
  created_at timestamp with time zone not null,
  processed_at timestamp with time zone
);

create index idx_exam_notice_created_at on exam_notice(created_at desc);
create index idx_exam_notice_status on exam_notice(status);
