spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/studyhub}
    username: ${DATABASE_USERNAME:studyhub}
    password: ${DATABASE_PASSWORD:studyhub}
    driver-class-name: org.postgresql.Driver
  flyway.locations: classpath:db/migration/common,classpath:db/migration/postgres
app.vector.provider: pgvector
